### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by jmrgz** [MASNathan/aliexpress-affiliate-php#1]
Hi! Sorry for asking, but I´m desperate to make this run.

I am always receiving invalid appKey key, but I got a working developer key. 

Do you know if it is deprecated?

I got an approved "Affiliates API" app at https://console.aliexpress.com/ but nor the sandbox or the normal API keys are working.

When manually calling this (replacing params), I receive "Invalid appKey":

http://gw.api.alibaba.com/openapi/param2/2/portals.open/api.getPromotionLinks/YOURAPIKEY?fields=totalResults,trackingId,publisherId,url,promotionUrl&trackingId=YOURTRACKINGIDHERE&urls=https://www.aliexpress.com/item/Rotary-Cheese-Tools-Cheese-Grater-Stainless-Steel-Slicer-Shreds-Drum-Hand-Held-Ginger-Graters-Cutter-Kitchen/32706493641.html

But when I test here, everything works:

https://developers.aliexpress.com/en/doc.htm?spm=a219a.7386653.0.0.66f59b71MHuRkg&docId=1&docType=15&apiName=aliexpress.affiliate.product.query

So I think I'm just missing something stupid. I have read during weeks about aliexpress affiliates API and I still do not know what fails.

Thank you in advance! :)

**Comment by MASNathan** [comment]
Hello @xamdam777 

This is probably deprecated since the code is over 3 years old.

Feel free to open a PR fixing the issue 😄

**Comment by jmrgz** [comment]
Thanks a lot for replying! their documentation is a mess and nothing works well for me, but I'll continue trying hard :)
